import { defineConfig, type UserConfig } from "vite-plus";

const config: UserConfig = defineConfig({
  fmt: {
    arrowParens: "avoid",
    ignorePatterns: ["src/simulation/arduplane.js"],
    printWidth: 80,
    sortImports: {},
  },
  lint: {
    categories: {
      correctness: "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    ignorePatterns: ["src/simulation/arduplane.js"],
    rules: {
      "no-case-declarations": "error",
      "no-empty": "error",
      "no-fallthrough": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "error",
      "no-unused-vars": "warn",
      "no-useless-assignment": "error",
      "no-var": "error",
      "preserve-caught-error": "error",
      "prefer-const": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "no-array-constructor": "error",
      "no-unused-expressions": ["error", { allowTaggedTemplates: true }],
      "arrow-body-style": ["error", "as-needed"],
      curly: ["error", "multi"],
      eqeqeq: "error",
      "func-style": ["error", "expression"],
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": "error",
      "prefer-destructuring": "error",
      "typescript/ban-ts-comment": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-namespace": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/only-throw-error": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/require-await": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/consistent-type-definitions": ["error", "type"],
      "typescript/consistent-type-imports": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-unnecessary-condition": [
        "error",
        {
          allowConstantLoopConditions: true,
        },
      ],
      "typescript/prefer-nullish-coalescing": "error",
    },
  },
});

export default config;
